module.exports = {
  lofiList: [
    "https://youtu.be/qqfMAf3IFE0",
    "https://youtu.be/I-RgNNaF8rw",
    "https://youtu.be/3_52H8bk9WQ",
    "https://youtu.be/XRyF-7jYMTc",
    "https://youtu.be/0vO5bPD5O-4",
    "https://youtu.be/mcNOdwAtN_w",
    "https://youtu.be/xpIQolDJ7sI",
    "https://youtu.be/8huKsgy70Bo",
    "https://youtu.be/bABNfwCGp4s",
    "https://youtu.be/-r0VtFGcuOU",
    "https://youtu.be/RXCNes55uo0",
    "https://youtu.be/6YUh8U5oypk",
    "https://youtu.be/9_-BAGI2EcA",
  ],
  musicList: [
    "https://youtu.be/W5ZCxHBh28k",
    "https://youtu.be/TZQsoLACMW0",
    "https://youtu.be/A9kTV-wpiWk",
    "https://youtu.be/_0s7qVLDiB4",
    "https://youtu.be/NdqM_oFRbz4",
    "https://youtu.be/Nq_AOktdhts",
    "https://youtu.be/o4Y0iwz2Y9U",
    "https://youtu.be/joPlzVJe2Cg",
    "https://youtu.be/NdqM_oFRbz4",
    "https://youtu.be/W6XHpvqHV2Q",
    "https://youtu.be/i1GGYR3qjek",
    "https://youtu.be/syqJAgTQdlU",
    "https://youtu.be/hwUGJXm02ZQ",
  ],
};
