module.exports = {
  phrases: [
    "Meu olhar é verdade, eu quero só você!",
    "Não fumo, não bebo e não cheiro. Só minto um pouco.",
    "O mundo só será bom no dia que todo o dinheiro acabar, mas que não me falte nenhum enquanto isso não acontece.",
    "Eu preciso descobrir a emoção de estar contigo.",
    "Na vida a gente tem que entender que um nasce pra sofrer enquanto o outro ri.",
    "O que eu quero? Sossego!",
    "A coisa que mais odeio é a hipocrisia. É a mentira da mentira.",
    "E eu gostava tanto de você!",
    "Eu preciso respirar o mesmo ar que te rodeia e na pele quero ter o mesmo sol que te bronzeia.",
    "O Roberto Carlos fala com as plantas, e depois o Tim Maia que é maluco.",
    "Com duas garrafas de uísque, canto até de manhã.",
    "Tudo é tudo e nada é nada!",
    'As pessoas costumam dizer: "O Tim Maia reclama pra cacete", mas alguém tem de reclamar.',
    "De repente a dor de esperar terminou e o amor veio, enfim.",
    "Mais grave! Mais agudo! Mais eco! Mais retorno! Mais tudo!",
    "Ah! Se o mundo inteiro me pudesse ouvir, tenho muito pra contar. Dizer que aprendi.",
    "Quando o inverno chegar, eu quero estar junto a ti. Pode o outono voltar, eu quero estar junto a ti.",
    "Não te troco nesta vida por ninguém, porque eu te quero bem.",
    "Quando a gente ama, não pensa em dinheiro. Só se quer amar.",
    "Se eu pudesse, só cantava. Quando eu paro de cantar, faço besteira.\nSe eu fosse dev... eu só codava. QUando eu paro de codar, faço besteira",
    "O segredo do meu sucesso é o equilíbrio: metade das minhas músicas é esquenta-sovaco e a outra metade é mela-cueca.",
    "Fiz uma dieta rigorosa. Cortei álcool, gorduras e açúcar. Em duas semanas perdi 14 dias",
    "A vida é o maior mistério e minha mente o maior mistério da vida.",
    "A sabedoria vem acompanhada da dor. E o desleixo vem acompanhado da desgraça.",
    "O Brasil é uma terra de mestiço pirado querendo ser puro-sangue.",
    "Gosto de cantar com sentimento. Se você não transmitir sentimento, não atinge ninguém.",
    "Aquele que com sabedoria alimenta a alma, fortalece-a e em nada o seu psicológico será abalado.",
    "A tristeza não existe. Quando estamos tristes, é porque a felicidade voltou a despistar-nos naquele longo caminho atrás dela.",
    "Este país não pode dar certo. Aqui prostituta se apaixona, cafetão tem ciúme, traficante se vicia e pobre é de direita",
  ],
};
