/**
 * O FABULOSO GERADOR DE LERO-LERO VERSÃO JAVASCRIPT (c)2001-2004 by Padre Levedo
 * Se quiser usar o código, use; porém deixe intacta esta nota de autoria!
 */

class TextGenerador {
  constructor() {
    this.init();
  }

  init() {
    this.validchars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz()_/!$";

    this.tab0 = [
      "Caros amigos, ",
      "Por outro lado, ",
      "Assim mesmo, ",
      "No entanto, não podemos esquecer que ",
      "Do mesmo modo, ",
      "A prática cotidiana prova que ",
      "Nunca é demais lembrar o peso e o significado destes problemas, uma vez que ",
      "Como Deleuze eloquentemente mostrou, ",
      "Acabei de provar que ",
      "Se estivesse vivo, Foucault diria que ",
      "Pretendo demonstrar que  ",
      "Neste sentido, existem duas tendências que coexistem de modo heterogêneo, revelando ",
      "Segundo Heidegger, ",
      "É lícito um filósofo restringir suas investigações ao mundo fenomênico, mas ",
      "Este pensamento está vinculado à desconstrução da metafísica, pois ",
      "Todas estas questões, devidamente ponderadas, levantam dúvidas sobre se ",
      "Pode-se argumentar, como Bachelard fizera, que ",			
      "Efetuando uma ruptura com Descartes, ",
      "Sob a perspectiva de Schopenhauer, ",
      "Segundo Nietzsche, ",
      "A situação parece particularmente favorável quando ",
      "Seguindo o fluxo da corrente analítica anglo-saxônica, ",
      "Em um dos seus momentos mais iluminados Heidegger afirmou que ",
      "O movimento inverso da proaíresis, que avança -pro-, como a pro-lépsis, demonstra que ",
      "Acima de tudo, é fundamental ressaltar que ",
      "O incentivo ao avanço tecnológico, assim como ",
      "Não obstante, ",
      "Pensando mais a longo prazo, ",
      "O que temos que ter sempre em mente é que ",
      "Ainda assim, existem dúvidas a respeito de como ",
      "Gostaria de enfatizar que ",
      "Todavia, ",
      "Correlativamente, por meio de suas teoria das pulsões, Freud mostra que ",
      "O empenho em analisar ",
      "Percebemos, cada vez mais, que ",
      "No mundo atual, ",
      "É importante questionar o quanto ",
      "Neste sentido, ",
      "Evidentemente, ",
      "Por conseguinte, ",
      "É claro que ",
      "Podemos já vislumbrar o modo pelo qual ",
      "Desta maneira, ",
      "O cuidado em identificar pontos críticos n",
      "A certificação de metodologias que nos auxiliam a lidar com ",
      "Antes de mais nada, ",
      "Poderia ser sugerido, entretanto, que ",
      "Estas considerações deixam claro que ",
      "Com base nesses argumentos, ",
      "Ora, ",
      "Se, todavia, ",
      "Se uma das premissas é assertórica e a outra, problemática, ",
      "Mas, à primeira vista, quiçá pareça que ",
      "Numa palavra, pois, com efeito, " ,
      "Neste momento o leitor deve reconhecer que acabei de demolir as bases da metafísica de Heidegger, pois  ",
      "Uma posição análoga, embora um tanto foucaultiana, defende que ",
      "Segundo a tese da eliminabilidade, ",
      "A proposta de Quine para este impasse se restringe a questionar ",
      "Entretanto, uma reflexão ulterior torna claro que ",
      "Deste modo, acabei de refutar a tese segundo a qual ",
      "Um teórico da redundância negaria que ",
      "Especificamente neste caso, a estratégia de Kant consiste em argumentar que ", 
      "Baseando-se  nos ensinamentos de Dewey, ",
      "Inevitavelmente, há muitas questões intrigantes sobre se ",
      "Deve-se produzir um conceito que ",
      "Prospectos designam, de início, ",
      "Se a própria desterritorialização relativa se projeta sobre ",
      "Mesmo o sujeito transcendental nos revela que ",
      "Este é um problema que remete tanto à Epistemologia platônica, quanto à Dialética hegeliana, tendo em vista que ",
      "O dualismo inegável de numerosos pontos evidencia o quanto ",
      "Essa busca de invariantes supõe um pressuposto existencial, assim como ",
      "As experiências acumuladas demonstram que ",
      "Se, para Sócrates, o homem não era mais que sua alma, podemos sustentar que ",
      "Ora, essa teoria é constituída como uma antropologia: ",
      "A instituição política, a rigor, atende a uma segunda função visando ",
      "Por fim, na sequência dessa espécie de introdução, ",
      "Desta maneira, o conflito da psique inconsciente, corrobora ",
      "Tendo em vista a extrema limitação dos meios empregados (como Husserl advertiu), ",
      "É lícito um filósofo restringir suas investigações ao mundo fenomênico, mas ",
      "Em primeiro lugar, ",
      "Levando em consideração as consequências da 'gramaticalidade' chomskyana, ",
      "Acima de tudo, ",
      "Numa série de artigos publicados entre 1843 e 1844, M.Hess sustenta que ",
      "Finalmente, por trás dessa questão do sujeito e da realidade ",
      "Contra esta teoria, que admite a realidade empírica do tempo,  ",
      "Porém, mais do que uma estética, ",
      "Contudo, a crítica contundente de Deleuze/Guatarri - dupla implacável - nos mostra que ",
      "Uma possível abordagem freudiana explicitaria que ",
      "De qualquer maneira, a análise de Foucault é definitiva: ",
      "É por isso que Baudrillard e Deleuze - em sua melhor forma - concordaram que ",
      "O filósofo francês Ricoeur, defende que ",
      "Baseado na tradição aristotélica, ",
      "Como Sartre diria, ",
      "A proposta de Heidegger para solucionar ",
      "O espírito dionisíaco da música e poesia nos ensinou que ",
      "A ruptura definitiva com Kant é consumada quando ",
      "O infinito virtual é possível no mundo, mas ",
      "De maneira sucinta, a interioridade do Ser social, eminentemente enquanto Ser, prova que ",
      "Bergson mostrou que os sistemas mecanicistas, ainda em voga, provocam ",
      "O imperativo da criação, o ímpeto do sistema, que realiza ",
      "Boécio, 'o último romano', nos mostra que ",
      "Wittgenstein - o primeiro - redigiu sua obra seminal se baseando no pressuposto de que ",
      "O primeiro Wittgenstein, ao contrário do segundo Wittgenstein, provou que ",
      "O segundo Wittgenstein (é importante não confundir com o primeiro Wittgenstein) nos mostrou que ",
      "O que caracteriza o relativismo, com efeito, é quando "
    ];

    this.tab1 = [
      "a infinita diversidade da realidade única ",
      "a complexidade dos estudos efetuados ",
      "a estrutura atual da ideação semântica ",
      "o novo modelo estruturalista aqui preconizado ",
      "a indeterminação contínua de distintas formas de fenômeno ",
      "a consolidação das estruturas psico-lógicas ",
      "o conceito de diáthesis e os princípios fundamentais de rhytmos e arrythmiston ",
      "o início da atividade geral de formação de conceitos ",
      "o desafiador cenário globalizado ",
      "o Übermensch de Nietzsche, ou seja, o Super-Homem, ",
      "a expansão dos mercados mundiais ",
      "a hegemonia do ambiente político ",
      "o fenômeno da Internet ",					
      "o aumento do diálogo entre os diferentes setores filosóficos ",
      "a crescente influência da mídia ",
      "a necessidade de renovação conceitual ",
      "o não-ser que não é nada "	,
      "o uno-múltiplo, repouso-movimento, finito indeterminado, ",
      "a instauração do modo aporético do Uno ",
      "a canalizaçao do Ser do Ente ",
      "a relevância do indivíduo singular na sociedade conflitante ",
      "o surgimento do comércio virtual ",
      "a revolução dos costumes ",
      "o acompanhamento das preferências de consumo ",
      "o comprometimento entre as ontologias ",
      "a determinação clara de objetivos ",
      "uma adoção de metodologias descentralizadoras ",
      "a valorização de fatores subjetivos ",
      "a percepção das dificuldades ",
      "o entendimento das metas propostas ",
      "o julgamento imparcial das quesões éticas ",
      "a coerência das idéias contratualistas ",
      "a origem de um sistema de coordenadas espaço-temporais singularmente compostas ",
      "a forma de uma transcendência imanente ou primordial",
      "o personagem conceitual imanente ao caos ",
      "o tríptico movimento de pensamento ",
      "o su-jeito de que fala Kant ",
      "a revolução copernicana, entendida como ruptura, ",
      "um juízo reflexionante do sujeito transcendental ",
      "a relevância da terceira antinomia da Antitética da Razão ",
      "o advento do Utilitarismo radical ",
      "a influência de elementos de ordem sociológica ",
      "o aspecto monádico da virtualização da realidade social ",
      "o axioma praedicatum inest subjectu ",
      "a relevância do formalismo lógico das instâncias predicativas ",
      "o monismo confuso característico de algumas vertentes contemporâneas ",
      "a consequência da interpretação substitucional dos quantificadores ",
      "a redutibilidade da aritmética à lógica ",
      "um forte compromisso ontológico com a teoria dos conjuntos ",
      "a teoria de Strawson, no final das contas, ",
      "o cálculo proposicional não-quantificado ",
      "a prossentença composta de invariantes lógicos ",					
      "a decisão resoluta (Entscholossenheit) ",
      "o Dasein, tornado manifesto, ",
      "a literalidade do texto, imanente ao autor, ",
      "o comportamento dialético dos processos considerados ",
      "a incompletude necessária de um sistema suficientemente abrangente ",
      "a abordagem de Zeit und Sein ",
      "o eidos platônico e a energeia (ato, utilidade) aristotélica ",
      "a univocidade da substância imanente ",
      "o objeto engendrado a priori ",
      "a elucidação dos pontos relacionais ",
      "a água talesiana reterritorializada ",
      "a bipolaridade do valor proposicional ",
      "a forma geral da proposição significativa ",
      "o mundo supra-celeste como modelo eterno ",
      "a Aporia como obstáculo cognitivo ",
      "a inversão do modelo hybris-nêmesis ",
      "a sustentabilidade do Cogito refutada ",
      "o sentido escatológico do mito de Fedro ",
      "a relevância atual da caverna platônica ",
      "um reaprofundamento das bases estéticas da vida intencional ",
      "a intencionalidade do sujeito volitivo ",
      "as três modalidades canônicas subjetivas ",
      "a enumeração exaustiva dos atos de linguagem não ",
      "o princípio de cooperação de Grice ",
      "o uso metafórico da linguagem, a respeito do significante e significado, ",
      "o silogismo hipotético, sob a perspectiva kantiana dos juízos infinitos, ",
      "a prática do bem-viver ",
      "o Apeiron de Anaximandro como uma infinidade ",
      "o Cosmos submetivo aos poderes do puro-devir ",
      "o domínio lógico destas questões, certamente relevantes, ",
      "o nominalismo enquanto princípio teórico ",
      "a expressão aparentemente plausível a priori ",
      "a hegemonia das categorias aristotélicas, durante todo o período medieval, ",
      "a refutação deste ponto de vista relativista ",
      "a criação de um sistema hilemórfico ",
      "o comprometimento da forma, tanto quanto da matéria, ",
      "a determinação do futuro status quo, a saber, uma condição de submissão das  estruturas de poder, ",
      "a ética antropomórfica da famigerada escola francesa ",
      "a consolidação das afecções no espírito ",
      "a universalidade eidética do puro-devir ",
      "a Vontade de Potência inerente ao ser humano, como Nietzsche destacou, ",
      "o sofrimento e tédio presentes em toda forma de vida, como Schopenhauer mostrou, ",
      "o Cristianismo entendido como degradação, na perspectiva universal do polêmico anticristo nietzscheano, não ",
      "o juízo analítico e o sintético a priori ",
      "o a priori histórico de uma experiência possível ",
      "a inter-independência da objetivação e subjetivação ",
      "o sujeito constituinte envolvido não ",
      "o ceticismo sistemático ",
      "a hegemonia das estruturas do poder repressivo ",
      "a mistificação e virtualização das massas ",
      "o entendimento dos universais antropológicos ",
      "a disfunção do mecanismo inconsciente ",
      "o desenvolvimento da consciência coletiva virtualizada ",
      "o mundo líquido em que vivemos ",
      "o surgimento de impulsos psicossociais individualizantes ",
      "a teoria das pulsões ",
      "a teoria do utilitarismo ",
      "a teoria da irredutibilidade ",
      "a eventual refutação da teoria quântica não ",
      "o objeto metapsicológico da razão ",
      "o modo de satisfação libidinal ",
      "o modo de satisfação libidinal sucessivo (oral, anal, fálico) ",
      "o acompanhamento do estágio pré-genital ",
      "o constante retorno do recalcado ",
      "a relação do sujeito com o objeto(recalcado) ",
      "a inacessibilidade dos processos mentais inconscientes ",
      "a implausibilidade da tábula rasa ",
      "o fenômeno da compulsão da repetição ",
      "a limitação dos poderes do narcisismo ",
      "uma mutação pós-jungiana ",
      "a escolha do objeto narcísico ",
      "a feminilidade como conceito analítico não ",
      "a pré-história pré-edipiana da menina ",
      "a teoria de Fliess ",
      "o complexo de castração, decorrente do Édipo feminino, ",
      "a constituição ígnea do substrato físico ",
      "a alteridade do rio heraclítico ",
      "o princípio de Heisenberg não ",
      "o princípio da extensionalidade ",
      "o princípio leibnizano da identidade dos indiscerníveis e indiscernibilidade dos idênticos ",
      "a desaceleração no caos ou no limiar de suspensão do infinito ",
      "a geração de sistemas de coordenadas heterogêneas irredutíveis ",
      "a referência capaz de atualizar o virtual ",
      "o véu de Maya, assim como a Vontade de Schopenhauer, ",
      "o plano de imanência pré-filosófico ",
      "o indivíduo em seu estado de natureza ",
      "o homem entendido como animal social ",
      "o conceito platônico de pólis ideal ",
      "a impossibilidade da possessão da verdade última "	
    ];

    this.tab2 = [
      "nos obriga à análise ",
      "cumpre um papel essencial na formulação ",
      "exige a precisão e a definição ",
      "auxilia a preparação e a composição ",
      "garante a contribuição de um grupo importante na determinação ",
      "assume importantes posições no estabelecimento ",
      "facilita a criação ",
      "obstaculiza a apreciação da importância ",
      "não oferece uma interessante oportunidade para verificação ",
      "acarreta um processo de reformulação e modernização ",
      "pode nos levar a considerar a reestruturação ",
      "representa uma abertura para a melhoria ",
      "ainda não demonstrou convincentemente como vai participar na mudança ",
      "talvez venha a ressaltar a relatividade ",
      "prepara-nos para enfrentar situações atípicas decorrentes ",
      "maximiza as possibilidades por conta ",
      "desafia a capacidade de equalização ",
      "agrega valor ao estabelecimento ",
      "é uma das consequências ",
      "promove a alavancagem ",
      "não pode mais se dissociar ",
      "possibilita uma melhor visão global ",
      "estimula a padronização ",
      "aponta para a melhoria ",
      "faz parte de um processo de agenciamento ",
      "não causa impacto indireto na reavaliação ",
      "apresenta tendências no sentido de aprovar a manutenção ",
      "estende o alcance e a importância ",
      "deve passar por modificações independentemente ",
      "afeta positivamente a correta previsão ",
      "nos obriga a inferir a invalidez ",
      "não parece corresponder a uma análise distributiva ",
      "define já o plano do espaço lógico ",
      "efetua a conexão habitual ",
      "parece compendiar nossas conclusões experimentais a respeito ",
      "implica que a condição necessária e suficiente ",
      "nos arrasta ao labirinto de sofismas obscuros ",
      "nos leva ao caminho impenetrável ",
      "obstaculiza a admissão de uma ontologia ",
      "demonstra a irrefutabilidade das vantagens ",
      "emprega uma noção de pressuposição ",
      "limita as atividades ",
      "vem corroborar as expectativas ",
      "tem que apresentar uma homogenidade em relação aos extremos ",
      "é condição necessária ",
      "é condição suficiente ",
      "é condição necessária e suficiente ",
      "constitui uma propriedade inalienável ",
      "impossibilita a adoção de medidas reabilitadoras ",
      "possibilita uma interpretação objetiva ",
      "não resulta em uma interiorização imanente ",
      "implica em uma interpretação subjetivista ",
      "é consequência de uma abordagem dogmática a respeito ",
      "é um subconjunto ",
      "verifica a validade ",
      "tem como componentes elementos indiscerníveis ",
      "reabilita a condição inicial ",
      "faz retroceder aos princípios ",
      "representa a expressão imediata ",
      "representa a essência ",
      "deve mostrar que é possível efetuar a intersubjetivação ",
      "permite um conhecimento geral de todo ser, sensível ou não sensível, ",
      "possibilita o ato de intenção consciente ",
      "corresponde à intuição das essências fenomenológicas ",
      "permite conceber uma ciência ",
      "não depreende-se de uma lógica do juízo, mas ",
      "se apresenta como experiência metapsicológica, devido à impermeabilização ",
      "designa o impulso psíquico cuja fonte está no corpo e cujo objetivo é a satisfação ",
      "não sistematiza essa relação, de tal modo que a pulsão funciona funciona como significado ",
      "não sistematiza a estrutura ",
      "institui o Complexo de Édipo, ordenando o sujeito com seu desejo e o interdito, em função ", 
      "é insuficiente para determinar as implicações ",
      "deve tratar sistematicamente ",
      "apreende a globalidade ",
      "reduz a importância ",
      "deverá confirmar as consequências decorrentes ",
      "resultou no abandono ",
      "pressupõe a admissão da existência a priori ",
      "compromete ontologicamente a teoria à existência ",
      "unificou os a priori sensíveis e intelectuais numa determinação recíproca ",
      "marca a autonomia do pensamento em relação ao fluxo ",
      "traz à tona uma construção transcendentalmente possível ",
      "recorre à experiência efetiva ",
      "estabelece o chamado princípio da subsidência em que demonstra o abaixamento gradual do fundo paralelamente à sedimentação ",
      "consistiria primeiramente em não pôr o acontecimento sob a autoridade de uma nova origem pura ",
      "consistiria primeiramente na autoridade ",
      "consistiria na origem epistemológica ",
      "permitiria a desconstrução ",
      "reduziria a importância ",
      "demonstraria a incompletude ",
      "justificaria a existência ",
      "justificaria a adoção ",
      "criaria um conflito no interior ",
      "potencializa a influência "
    ];

    this.tab3 = [
      "das condições epistemológicas e cognitivas exigidas.",
      "da fundamentação metafísica das representações.",
      "do sistema de conhecimento geral.",
      "das posturas dos filósofos divergentes com relação às atribuições conceituais.",
      "das novas teorias propostas.",
      "das direções preferenciais no sentido do progresso filosófico.",
      "do sistema de formação de quadros que corresponde às necessidades lógico-estruturais.",
      "dos paradigmas filosóficos.",
      "dos relacionamentos verticais entre as hierarquias conceituais.",
      "do processo de comunicação como um todo.",
      "das ciências discursivas.",
      "das relações entre o conteúdo proposicional e o figurado.",
      "das múltiplas direções do ponto de transcendência do sentido enunciativo.",
      "de universos de Contemplação, espelhados na arte minimalista e no expressionismo abstrato, absconditum.",
      "de todos os recursos funcionais envolvidos.",
      "da corrente inovadora da qual fazemos parte.",
      "das considerações acima? Nada se pode dizer, pois sobre o que não se pode falar, deve-se calar.",
      "do fluxo de informações.",
      "dos elementos envolvidos de maneira conclusiva? Nada se pode dizer a respeito.",
      "das diversas correntes de pensamento.",
      "das regras de conduta normativas.",
      "da conjuntura histórico-social.",
      "do retorno esperado a longo prazo.",
      "do investimento em reciclagem ideológica.",
      "de um remanejamento dos quadros conceituais.",
      "da coisa-em-si, entendida como substância retrocedente.",
      "das coisas e o melhor dos mundos possíveis.",
      "da sensibilia dos não-sentidos.",
      "dos sinais peirceanos percebidos pelo sujeito imerso nos fenômenos sociais.",
      "da doxa, da opinião e da razão pura do espírito transcendente.",
      "do homem verdadeiramente virtuoso.",
      "de conhecimentos empíricos provindos das afecções.",
      "dos prospectos condicionalizantes e necessários a todo juízo empírico.",
      "das três instâncias de oposição centrais.",
      "da determinação do Ser enquanto Ser.",
      "da afirmação que o Ser é e o Não ser não é.",
      "da esfera do virtual, a saber, do pensamento em potência.",
      "de um mundo povoado por objetos intencionais e transcendentes, interiores ao imanente infinito.",
      "das retroações, proliferações, conexões e fractalizações do território desterritorializado.",
      "dos modos de análise convencionais.",
      "de alternativas às soluções ortodoxas.",
      "do gênio grego fundado na poesia homérica.",
      "da turbulência do acaso-caos lançado sobre o universo infinito que envolve o mundo extra-mental.",
      "das convicções empiristas. ",
      "de uma metafísica da presença? Cabe ao leitor julgar.",
      "do movimento in loco da desterritorialização indiscernível.",
      "do Deus transcendente a toda sensação e intuição cognitiva.",
      "dos conceitos de propriedade e cidadania.",
      "dos princípios da ética normativa deontológica.",
      "dos argumentos pró-dêiticos de uma visão subjetivista da ética teleológica.",
      "do antiplatonismo fichteano resultante dos movimentos revolucionários de então.",
      "da humanização do sujeito e da animalização do homem.",
      "das ilusões transcendentais presentes na obra de Condillac.",
      "da substância aristotélica fundida com o solipsismo cartesiano em função de uma perspectiva dialético-social.",
      "do fundo comum da humanidade.",
      "do conjunto de todos os conjuntos que não se contêm a si próprios como membro.",
      "do ponto de vista da história da filosofia continental.",
      "da dissimetria dos dois tipos de polissemia epistêmica.",
      "da cartografia dessa rede urbana de ligações subterrâneas.",
      "do exercício do poder opressor sobre a parcela defasada do proletariado.",
      "das vivências da subjetividade vertical e defasada pós-moderna.",
      "da incompatibilidade do próprio pensamento de Hegel e Foucault.",
      "do realismo ingênuo, isto é, da crença equivocada na confiabilidade dos dados sensoriais transmitidos pela realidade fenomenal.",
      "da transposição do Outro em detrimento de uma unidade social revolucionária.",
      "do tempo e do espaço entendido como a priori sintético.",
      "do dualismo ontológico das filosofias pré-hegelianas? Deixemos a questão em aberto.",
      "do levantamento das variáveis envolvidas.",
        "da substancialidade e causalidade entendidos como certezas fundamentais.",
      "da lógica da aparência, psicologia racional, cosmologia racional e, por fim, da teologia racional.",
      "da lógica polivalente aplicada às pesquisas, em particular, a Fuzzy Logic.",
      "da doutrina do esquematismo trancendental aplicada aos dias atuais.",
      "da dissociação entre o político e o religioso.",
      "dos meios de comunicação, The Media, o fator condicionante da interdependência virtual.",
      "da experimentação sem experimentação real, preconizada na pós-modernidade.",
      "da pintura monocromática do pintor pós-moderno.",
      "dos conhecimentos a priori.",
      "da linguagem privada. ",
      "da hipótese de que existem infinitos objetos.",
      "dos paradoxos de Zenão, amparados em uma proposta logicista.",
      "das figuras sociais quanto sujeitos submetidos às estruturas de poder.",
      "dos valores morais decorrentes de uma tradição normativa.",
      "do liberalismo extremo, vulgo neoliberalismo avançado, imanente nos procedimentos atuais.",
      "da velocidade infinita do spin das partículas.",
      "da materialização do ser, em objetos visíveis, e da imaterialização do Não-ser, em não-objetos.",
      "do observador de Einstein ou de Heinsenberg.",
      "do demônio de Laplace.",			
      "da aparição não-cromática do som em um continuum infinito.",
      "das condições de suas incógnitas.",
      "das definições conceituais da matéria.",
      "dos conceitos nominalistas.",
      "da definição espinosista de substância.",
      "do aparelho repressivo, coercitivo, do sistema.",
      "dos métodos utilizados na busca da verdade.",
      "da velha terra grega fraturada.",
      "do paradoxo endo-referencial, apontado por Russel, na teoria dos conjuntos de Cantor.",
      "do direito romano.",
      "da condição de verdade de proposições elementares como ((p ^ ~q) -> (~r v (p <-> r))).",
      "dos limites da ação do Estado.",
      "da interpretação de fatos socio-linguisticos.",
      "da teologia positiva empregada em movimentos negativos.",
      "das alternâncias entre pensamentos sábios e não-sábios.",
      "da natureza não-filosófica dos conceitos.",
      "da fórmula da ressonância racionalista.",
      "dos testes de falseabilidade das teorias científicas.",
      "do prazer e da dor."
    ];

    // eslint-disable-next-line no-extend-native
    Array.prototype.shuffle = function() {
      var temp;
      var a, b;
    
      if (this.length < 2) return;
    
      for (let i=0; i < 20; i++) {
        a = Math.floor(Math.random() * this.length);
        b = Math.floor(Math.random() * this.length);
        temp = this[a];
        this[a] = this[b];
        this[b] = temp;
      }
    }

    // eslint-disable-next-line no-extend-native
    Array.prototype.chr = function(index, pos) {
      return this[index].charAt(pos);
    }
  }

  lerolero(lines) {
    let text = ""
		let firstshot = 1;
		let paragraph = 0;
		while(lines > 0) {
			if (firstshot === 1) {
				if (lines % 101 === 0 && lines % 19 === 0) {
					text += this.tab0.chr(1,0)+this.tab0.chr(0,1)+this.tab3.chr(0,0)+this.tab2.chr(11,21)+this.tab2.chr(2,0)+this.tab3.chr(20,3)+this.tab1.chr(16,15)+this.tab0.chr(7,3)+this.tab3.chr(22,25)+this.tab1.chr(28,6)+this.tab1.chr(15,13)+this.tab3.chr(2,1)+this.tab3.chr(0,3)+this.validchars.charAt(52)+this.validchars.charAt(48)+this.validchars.charAt(48)+this.validchars.charAt(48)+this.tab3.chr(4,21)+this.tab2.chr(10,0)+this.tab0.chr(0,1)+this.tab3.chr(0,0)+this.tab2.chr(11,21)+this.tab3.chr(2,7)+this.tab1.chr(16,15)+this.tab0.chr(7,3)+this.tab3.chr(22,25)+this.tab1.chr(28,6)+this.tab1.chr(15,13)+this.tab3.chr(2,1)+this.tab3.chr(4,21)+this.tab1.chr(13,2)+this.tab3.chr(19,4)+this.tab2.chr(17,1)+this.tab3.chr(9,18)+this.tab2.chr(1,0)+this.tab0.chr(14,38)+this.tab1.chr(0, 31)+this.tab3.chr(9,18)+this.tab2.chr(11,16)+this.tab1.chr(4,17)+this.validchars.charAt(53)
					break;
				}

				firstshot = 0;
			}

			this.tab0.shuffle();
			this.tab1.shuffle();
			this.tab2.shuffle();
			this.tab3.shuffle();

			for (let i = 0; i < this.tab0.length; i++) {
				if (paragraph === 0) {
					text += "\n"
				}

				text += this.tab0[i]+this.tab1[i]+this.tab2[i]+this.tab3[i]+" "

				if (++paragraph >= (2+ Math.ceil(Math.random() * 3))) {
					paragraph = 0;
				}

				if (--lines <= 0) break;
			}
    }
    
    return text;
  }
}

export default new TextGenerador();